name: weather_app
description: "The Test Weather API for Flutter. by grafscorp"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  weather: 
    ^3.1.1
  intl: ^0.19.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons:
    ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/WeatherAppIcon.png"
flutter:
  uses-material-design: true

  assets:
    - assets/images/sunset.png
    - assets/images/sunrise.png
    